site_name: "PRISM: A ROGUELIKE ENGINE"
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Architecture Primer: architecture-primer.md
  - Making a roguelike:
    - Part 01: making-a-roguelike-part1.md

