site_name: "PRISM: A ROGUELIKE ENGINE"
theme:
  name: terminal
nav:
  - Home: index.md
  - Documentation: doc.md
  - Architecture Primer: architecture-primer.md
  - Making a roguelike:
    - Part 01: making-a-roguelike-part1.md
  - API:
    - action: api/action.md
    - actiondecision: api/actiondecision.md
    - actionmessage: api/actionmessage.md
    - actor: api/actor.md
    - actorstorage: api/actorstorage.md
    - arg: api/arg.md
    - assert: api/assert.md
    - bitmaskbuffer: api/bitmaskbuffer.md
    - boolean: api/boolean.md
    - booleanbuffer: api/booleanbuffer.md
    - boundingbox: api/boundingbox.md
    - btconditional: api/btconditional.md
    - btnode: api/btnode.md
    - btroot: api/btroot.md
    - btselector: api/btselector.md
    - btsequence: api/btsequence.md
    - btsucceeder: api/btsucceeder.md
    - button: api/button.md
    - buttonprops: api/buttonprops.md
    - camera: api/camera.md
    - cell: api/cell.md
    - collectgarbage: api/collectgarbage.md
    - collidercomponent: api/collidercomponent.md
    - collideroptions: api/collideroptions.md
    - collisionmask: api/collisionmask.md
    - color4: api/color4.md
    - component: api/component.md
    - controllercomponent: api/controllercomponent.md
    - coroutine: api/coroutine.md
    - coroutinelib: api/coroutinelib.md
    - debug: api/debug.md
    - debuginfo: api/debuginfo.md
    - debuglib: api/debuglib.md
    - debugmessage: api/debugmessage.md
    - decision: api/decision.md
    - display: api/display.md
    - distancetype: api/distancetype.md
    - dofile: api/dofile.md
    - drawablecomponent: api/drawablecomponent.md
    - editor: api/editor.md
    - editorgrid: api/editorgrid.md
    - editorgridinit: api/editorgridinit.md
    - editorgridprops: api/editorgridprops.md
    - editorroot: api/editorroot.md
    - editorrootprops: api/editorrootprops.md
    - editorstate: api/editorstate.md
    - ellipsemodification: api/ellipsemodification.md
    - ellipsetool: api/ellipsetool.md
    - erasemodification: api/erasemodification.md
    - erasetool: api/erasetool.md
    - filepanel: api/filepanel.md
    - filepanelinit: api/filepanelinit.md
    - filepanelprops: api/filepanelprops.md
    - filetype: api/filetype.md
    - fill: api/fill.md
    - fraction: api/fraction.md
    - function: api/function.md
    - gamestate: api/gamestate.md
    - gamestatemanager: api/gamestatemanager.md
    - geometer: api/geometer.md
    - grid: api/grid.md
    - ibehavior: api/ibehavior.md
    - keybinding: api/keybinding.md
    - level: api/level.md
    - levelstate: api/levelstate.md
    - linemodification: api/linemodification.md
    - linetool: api/linetool.md
    - map: api/map.md
    - mapbuilder: api/mapbuilder.md
    - mapgeneratorstate: api/mapgeneratorstate.md
    - message: api/message.md
    - modification: api/modification.md
    - neighborhood: api/neighborhood.md
    - object: api/object.md
    - opaquecomponent: api/opaquecomponent.md
    - pastemodification: api/pastemodification.md
    - penmodification: api/penmodification.md
    - pentool: api/pentool.md
    - placeable: api/placeable.md
    - playercontrollercomponent: api/playercontrollercomponent.md
    - prefabeditorstate: api/prefabeditorstate.md
    - priorityqueue: api/priorityqueue.md
    - prism: api/prism.md
    - quadrant: api/quadrant.md
    - queue: api/queue.md
    - rectmodification: api/rectmodification.md
    - recttool: api/recttool.md
    - rng: api/rng.md
    - row: api/row.md
    - scheduler: api/scheduler.md
    - selectiongrid: api/selectiongrid.md
    - selectiongridinit: api/selectiongridinit.md
    - selectiongridprops: api/selectiongridprops.md
    - selectionpanel: api/selectionpanel.md
    - selectionpanelinit: api/selectionpanelinit.md
    - selectionpanelprops: api/selectionpanelprops.md
    - selecttool: api/selecttool.md
    - sensescomponent: api/sensescomponent.md
    - sensessystem: api/sensessystem.md
    - sensestracker: api/sensestracker.md
    - simplescheduler: api/simplescheduler.md
    - sparsearray: api/sparsearray.md
    - sparsegrid: api/sparsegrid.md
    - sparsemap: api/sparsemap.md
    - spectrum: api/spectrum.md
    - spectrumattachable: api/spectrumattachable.md
    - spriteatlas: api/spriteatlas.md
    - system: api/system.md
    - systemmanager: api/systemmanager.md
    - target: api/target.md
    - textinput: api/textinput.md
    - textinputinit: api/textinputinit.md
    - textinputprops: api/textinputprops.md
    - tileelement: api/tileelement.md
    - tileelementprops: api/tileelementprops.md
    - tool: api/tool.md
    - tools: api/tools.md
    - toolsprops: api/toolsprops.md
    - unfloatselectionmodification: api/unfloatselectionmodification.md
    - vector2: api/vector2.md
markdown_extensions:
  - pymdownx.superfences         # required extension
  - pymdownx.highlight:
      use_pygments: true         # use pygments library    
      pygments_style: sas        # use 'default' style
      noclasses: true            # update HTML style attr
  - pymdownx.inlinehilite        # style inline code
