name: Docs CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v2

      - name: Deploy Docs
        working-directory: docs
        run: |
          pip install mkdocs
          pip install mkdocs-terminal
          mkdocs gh-deploy --strict --force
